grafana:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
      - grafana.kunkels.me
    tls:
      - hosts:
          - grafana.kunkels.me
        secretName: tls-grafana-kunkels-me
