on:
  push:
    branches:
      - "**"

env:
  TERRAFORM_VERSION: 1.0.9

jobs:
  terraform-fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: $TERRAFORM_VERSION
      - run: terraform fmt -check -recursive

  terraform-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: $TERRAFORM_VERSION
      - run: terraform init -backend=false
      - run: terraform validate
